var annotated_dup =
[
    [ "Projekt", "namespace_projekt.html", [
      [ "Miscellaneous", "namespace_projekt_1_1_miscellaneous.html", [
        [ "Converters", "namespace_projekt_1_1_miscellaneous_1_1_converters.html", [
          [ "AllCollapsedToCollapsedConverter", "class_projekt_1_1_miscellaneous_1_1_converters_1_1_all_collapsed_to_collapsed_converter.html", null ]
        ] ],
        [ "DatabaseHandler", "class_projekt_1_1_miscellaneous_1_1_database_handler.html", "class_projekt_1_1_miscellaneous_1_1_database_handler" ],
        [ "IHashingHandler", "interface_projekt_1_1_miscellaneous_1_1_i_hashing_handler.html", null ],
        [ "LoginWrapper", "class_projekt_1_1_miscellaneous_1_1_login_wrapper.html", "class_projekt_1_1_miscellaneous_1_1_login_wrapper" ],
        [ "NotifyTaskCompletion< TResult >", "class_projekt_1_1_miscellaneous_1_1_notify_task_completion-1-g.html", null ],
        [ "ObservableObject", "class_projekt_1_1_miscellaneous_1_1_observable_object.html", "class_projekt_1_1_miscellaneous_1_1_observable_object" ]
      ] ],
      [ "Models", "namespace_projekt_1_1_models.html", [
        [ "BaseTableModel", "class_projekt_1_1_models_1_1_base_table_model.html", null ],
        [ "ExtendedStudentModel", "class_projekt_1_1_models_1_1_extended_student_model.html", "class_projekt_1_1_models_1_1_extended_student_model" ],
        [ "FacultyModel", "class_projekt_1_1_models_1_1_faculty_model.html", "class_projekt_1_1_models_1_1_faculty_model" ],
        [ "GroupCreateModel", "class_projekt_1_1_models_1_1_group_create_model.html", null ],
        [ "GroupDeleteModel", "class_projekt_1_1_models_1_1_group_delete_model.html", null ],
        [ "GroupEditModel", "class_projekt_1_1_models_1_1_group_edit_model.html", null ],
        [ "GroupStudentModel", "class_projekt_1_1_models_1_1_group_student_model.html", "class_projekt_1_1_models_1_1_group_student_model" ],
        [ "ITable", "interface_projekt_1_1_models_1_1_i_table.html", null ],
        [ "LessonModel", "class_projekt_1_1_models_1_1_lesson_model.html", null ],
        [ "LoginModel", "class_projekt_1_1_models_1_1_login_model.html", null ],
        [ "MajorDataModel", "class_projekt_1_1_models_1_1_major_data_model.html", "class_projekt_1_1_models_1_1_major_data_model" ],
        [ "MajorModel", "class_projekt_1_1_models_1_1_major_model.html", "class_projekt_1_1_models_1_1_major_model" ],
        [ "PlaceCreateModel", "class_projekt_1_1_models_1_1_place_create_model.html", null ],
        [ "PlaceModel", "class_projekt_1_1_models_1_1_place_model.html", null ],
        [ "SubjectModel", "class_projekt_1_1_models_1_1_subject_model.html", null ],
        [ "UserModel", "class_projekt_1_1_models_1_1_user_model.html", null ]
      ] ],
      [ "ViewModels", "namespace_projekt_1_1_view_models.html", [
        [ "Behaviors", "namespace_projekt_1_1_view_models_1_1_behaviors.html", [
          [ "DataGridSelectedCellBehavior", "class_projekt_1_1_view_models_1_1_behaviors_1_1_data_grid_selected_cell_behavior.html", null ]
        ] ],
        [ "ConditionalContentControlViewModel", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model.html", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model" ],
        [ "CurrentProfileViewModel", "class_projekt_1_1_view_models_1_1_current_profile_view_model.html", null ],
        [ "DegreeCreateViewModel", "class_projekt_1_1_view_models_1_1_degree_create_view_model.html", null ],
        [ "FacultyCreateViewModel", "class_projekt_1_1_view_models_1_1_faculty_create_view_model.html", null ],
        [ "FacultyEditViewModel", "class_projekt_1_1_view_models_1_1_faculty_edit_view_model.html", null ],
        [ "GroupCreateViewModel", "class_projekt_1_1_view_models_1_1_group_create_view_model.html", null ],
        [ "GroupDeleteViewModel", "class_projekt_1_1_view_models_1_1_group_delete_view_model.html", null ],
        [ "GroupEditViewModel", "class_projekt_1_1_view_models_1_1_group_edit_view_model.html", null ],
        [ "GroupStudentViewModel", "class_projekt_1_1_view_models_1_1_group_student_view_model.html", "class_projekt_1_1_view_models_1_1_group_student_view_model" ],
        [ "GroupSubjectCoordinatorViewModel", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model.html", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model" ],
        [ "GroupViewTableViewModel", "class_projekt_1_1_view_models_1_1_group_view_table_view_model.html", null ],
        [ "IndexableProperty< T >", "class_projekt_1_1_view_models_1_1_indexable_property-1-g.html", null ],
        [ "IPageViewModel", "interface_projekt_1_1_view_models_1_1_i_page_view_model.html", null ],
        [ "ITable", "interface_projekt_1_1_view_models_1_1_i_table.html", null ],
        [ "LessonsCreateViewModel", "class_projekt_1_1_view_models_1_1_lessons_create_view_model.html", null ],
        [ "LessonsDeleteViewModel", "class_projekt_1_1_view_models_1_1_lessons_delete_view_model.html", null ],
        [ "LessonsEditViewModel", "class_projekt_1_1_view_models_1_1_lessons_edit_view_model.html", null ],
        [ "LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
        [ "MainMenuViewModel", "class_projekt_1_1_view_models_1_1_main_menu_view_model.html", null ],
        [ "MainWindowViewModel", "class_projekt_1_1_view_models_1_1_main_window_view_model.html", null ],
        [ "MajorManagmentViewModel", "class_projekt_1_1_view_models_1_1_major_managment_view_model.html", "class_projekt_1_1_view_models_1_1_major_managment_view_model" ],
        [ "PlaceCreateViewModel", "class_projekt_1_1_view_models_1_1_place_create_view_model.html", null ],
        [ "PlaceDeleteViewModel", "class_projekt_1_1_view_models_1_1_place_delete_view_model.html", null ],
        [ "PlaceEditViewModel", "class_projekt_1_1_view_models_1_1_place_edit_view_model.html", null ],
        [ "PlaceViewTableViewModel", "class_projekt_1_1_view_models_1_1_place_view_table_view_model.html", null ],
        [ "RelayCommand", "class_projekt_1_1_view_models_1_1_relay_command.html", "class_projekt_1_1_view_models_1_1_relay_command" ],
        [ "SubjectCreateViewModel", "class_projekt_1_1_view_models_1_1_subject_create_view_model.html", null ],
        [ "SubjectDeleteViewModel", "class_projekt_1_1_view_models_1_1_subject_delete_view_model.html", null ],
        [ "SubjectEditViewModel", "class_projekt_1_1_view_models_1_1_subject_edit_view_model.html", null ],
        [ "SubjectViewTableViewModel", "class_projekt_1_1_view_models_1_1_subject_view_table_view_model.html", null ],
        [ "TableViewModel", "class_projekt_1_1_view_models_1_1_table_view_model.html", null ],
        [ "TwoDataGridsViewModel", "class_projekt_1_1_view_models_1_1_two_data_grids_view_model.html", "class_projekt_1_1_view_models_1_1_two_data_grids_view_model" ],
        [ "TwoListBoxesViewModel", "class_projekt_1_1_view_models_1_1_two_list_boxes_view_model.html", null ],
        [ "UsersCreateViewModel", "class_projekt_1_1_view_models_1_1_users_create_view_model.html", null ],
        [ "UsersDeleteViewModel", "class_projekt_1_1_view_models_1_1_users_delete_view_model.html", null ],
        [ "UsersEditViewModel", "class_projekt_1_1_view_models_1_1_users_edit_view_model.html", null ]
      ] ],
      [ "Views", "namespace_projekt_1_1_views.html", [
        [ "ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", "class_projekt_1_1_views_1_1_conditional_content_control" ],
        [ "CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", "class_projekt_1_1_views_1_1_current_profile_view" ],
        [ "DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", "class_projekt_1_1_views_1_1_degree_create_view" ],
        [ "FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", "class_projekt_1_1_views_1_1_faculty_create_view" ],
        [ "GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", "class_projekt_1_1_views_1_1_group_create_view" ],
        [ "GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", "class_projekt_1_1_views_1_1_group_delete_view" ],
        [ "GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", "class_projekt_1_1_views_1_1_group_edit_view" ],
        [ "GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", "class_projekt_1_1_views_1_1_group_student_view" ],
        [ "GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", "class_projekt_1_1_views_1_1_group_subject_coordinator_view" ],
        [ "GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", "class_projekt_1_1_views_1_1_group_table_view" ],
        [ "LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", "class_projekt_1_1_views_1_1_lessons_create_view" ],
        [ "LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", "class_projekt_1_1_views_1_1_lessons_delete_view" ],
        [ "LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", "class_projekt_1_1_views_1_1_lessons_edit_view" ],
        [ "LoginView", "class_projekt_1_1_views_1_1_login_view.html", "class_projekt_1_1_views_1_1_login_view" ],
        [ "MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", "class_projekt_1_1_views_1_1_main_menu_view" ],
        [ "MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", "class_projekt_1_1_views_1_1_main_window_view" ],
        [ "MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", "class_projekt_1_1_views_1_1_major_managment_view" ],
        [ "PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", "class_projekt_1_1_views_1_1_place_creator_view" ],
        [ "PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", "class_projekt_1_1_views_1_1_place_delete_view" ],
        [ "PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", "class_projekt_1_1_views_1_1_place_edit_view" ],
        [ "PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", "class_projekt_1_1_views_1_1_place_table_view" ],
        [ "SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", "class_projekt_1_1_views_1_1_subject_create_view" ],
        [ "SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", "class_projekt_1_1_views_1_1_subject_delete_view" ],
        [ "SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", "class_projekt_1_1_views_1_1_subject_edit_view" ],
        [ "SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", "class_projekt_1_1_views_1_1_subject_table_view" ],
        [ "TableView", "class_projekt_1_1_views_1_1_table_view.html", "class_projekt_1_1_views_1_1_table_view" ],
        [ "TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", "class_projekt_1_1_views_1_1_time_table_view" ],
        [ "TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", "class_projekt_1_1_views_1_1_two_data_grids_view" ],
        [ "TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", "class_projekt_1_1_views_1_1_two_list_boxes_view" ],
        [ "UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", "class_projekt_1_1_views_1_1_users_create_view" ],
        [ "UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", "class_projekt_1_1_views_1_1_users_delete_view" ],
        [ "UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", "class_projekt_1_1_views_1_1_users_edit_view" ]
      ] ],
      [ "App", "class_projekt_1_1_app.html", "class_projekt_1_1_app" ]
    ] ],
    [ "XamlGeneratedNamespace", "namespace_xaml_generated_namespace.html", [
      [ "GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", "class_xaml_generated_namespace_1_1_generated_internal_type_helper" ]
    ] ]
];