var hierarchy =
[
    [ "Application", null, [
      [ "Projekt.App", "class_projekt_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Application", null, [
      [ "Projekt.App", "class_projekt_1_1_app.html", null ],
      [ "Projekt.App", "class_projekt_1_1_app.html", null ]
    ] ],
    [ "Behavior", null, [
      [ "Projekt.ViewModels.Behaviors.DataGridSelectedCellBehavior", "class_projekt_1_1_view_models_1_1_behaviors_1_1_data_grid_selected_cell_behavior.html", null ]
    ] ],
    [ "Projekt.Miscellaneous.DatabaseHandler", "class_projekt_1_1_miscellaneous_1_1_database_handler.html", null ],
    [ "Projekt.Models.ExtendedStudentModel", "class_projekt_1_1_models_1_1_extended_student_model.html", null ],
    [ "ICommand", null, [
      [ "Projekt.ViewModels.RelayCommand", "class_projekt_1_1_view_models_1_1_relay_command.html", null ]
    ] ],
    [ "System.Windows.Markup.IComponentConnector", null, [
      [ "Projekt.Views.ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", null ],
      [ "Projekt.Views.ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", null ],
      [ "Projekt.Views.CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", null ],
      [ "Projekt.Views.CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", null ],
      [ "Projekt.Views.DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", null ],
      [ "Projekt.Views.DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", null ],
      [ "Projekt.Views.FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", null ],
      [ "Projekt.Views.FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", null ],
      [ "Projekt.Views.GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", null ],
      [ "Projekt.Views.GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", null ],
      [ "Projekt.Views.GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", null ],
      [ "Projekt.Views.GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", null ],
      [ "Projekt.Views.GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", null ],
      [ "Projekt.Views.GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", null ],
      [ "Projekt.Views.GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", null ],
      [ "Projekt.Views.GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", null ],
      [ "Projekt.Views.GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", null ],
      [ "Projekt.Views.GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", null ],
      [ "Projekt.Views.GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", null ],
      [ "Projekt.Views.GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", null ],
      [ "Projekt.Views.LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", null ],
      [ "Projekt.Views.LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", null ],
      [ "Projekt.Views.LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", null ],
      [ "Projekt.Views.LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", null ],
      [ "Projekt.Views.LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", null ],
      [ "Projekt.Views.LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", null ],
      [ "Projekt.Views.LoginView", "class_projekt_1_1_views_1_1_login_view.html", null ],
      [ "Projekt.Views.LoginView", "class_projekt_1_1_views_1_1_login_view.html", null ],
      [ "Projekt.Views.MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", null ],
      [ "Projekt.Views.MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", null ],
      [ "Projekt.Views.MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", null ],
      [ "Projekt.Views.MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", null ],
      [ "Projekt.Views.MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", null ],
      [ "Projekt.Views.MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", null ],
      [ "Projekt.Views.PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", null ],
      [ "Projekt.Views.PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", null ],
      [ "Projekt.Views.PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", null ],
      [ "Projekt.Views.PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", null ],
      [ "Projekt.Views.PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", null ],
      [ "Projekt.Views.PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", null ],
      [ "Projekt.Views.PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", null ],
      [ "Projekt.Views.PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", null ],
      [ "Projekt.Views.SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", null ],
      [ "Projekt.Views.SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", null ],
      [ "Projekt.Views.SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", null ],
      [ "Projekt.Views.SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", null ],
      [ "Projekt.Views.SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", null ],
      [ "Projekt.Views.SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", null ],
      [ "Projekt.Views.SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", null ],
      [ "Projekt.Views.SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", null ],
      [ "Projekt.Views.TableView", "class_projekt_1_1_views_1_1_table_view.html", null ],
      [ "Projekt.Views.TableView", "class_projekt_1_1_views_1_1_table_view.html", null ],
      [ "Projekt.Views.TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", null ],
      [ "Projekt.Views.TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", null ],
      [ "Projekt.Views.TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", null ],
      [ "Projekt.Views.TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", null ],
      [ "Projekt.Views.TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", null ],
      [ "Projekt.Views.TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", null ],
      [ "Projekt.Views.UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", null ],
      [ "Projekt.Views.UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", null ],
      [ "Projekt.Views.UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", null ],
      [ "Projekt.Views.UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", null ],
      [ "Projekt.Views.UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", null ],
      [ "Projekt.Views.UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", null ]
    ] ],
    [ "IEquatable", null, [
      [ "Projekt.Models.MajorModel", "class_projekt_1_1_models_1_1_major_model.html", null ]
    ] ],
    [ "Projekt.Miscellaneous.IHashingHandler", "interface_projekt_1_1_miscellaneous_1_1_i_hashing_handler.html", null ],
    [ "IMultiValueConverter", null, [
      [ "Projekt.Miscellaneous.Converters.AllCollapsedToCollapsedConverter", "class_projekt_1_1_miscellaneous_1_1_converters_1_1_all_collapsed_to_collapsed_converter.html", null ]
    ] ],
    [ "Projekt.ViewModels.IndexableProperty< T >", "class_projekt_1_1_view_models_1_1_indexable_property-1-g.html", null ],
    [ "INotifyPropertyChanged", null, [
      [ "Projekt.Miscellaneous.ObservableObject", "class_projekt_1_1_miscellaneous_1_1_observable_object.html", [
        [ "Projekt.Miscellaneous.LoginWrapper", "class_projekt_1_1_miscellaneous_1_1_login_wrapper.html", null ],
        [ "Projekt.Miscellaneous.NotifyTaskCompletion< TResult >", "class_projekt_1_1_miscellaneous_1_1_notify_task_completion-1-g.html", null ],
        [ "Projekt.Models.BaseTableModel", "class_projekt_1_1_models_1_1_base_table_model.html", [
          [ "Projekt.Models.GroupCreateModel", "class_projekt_1_1_models_1_1_group_create_model.html", null ],
          [ "Projekt.Models.GroupDeleteModel", "class_projekt_1_1_models_1_1_group_delete_model.html", null ],
          [ "Projekt.Models.GroupEditModel", "class_projekt_1_1_models_1_1_group_edit_model.html", null ],
          [ "Projekt.Models.GroupStudentModel", "class_projekt_1_1_models_1_1_group_student_model.html", null ],
          [ "Projekt.Models.PlaceCreateModel", "class_projekt_1_1_models_1_1_place_create_model.html", null ]
        ] ],
        [ "Projekt.Models.FacultyModel", "class_projekt_1_1_models_1_1_faculty_model.html", null ],
        [ "Projekt.Models.LessonModel", "class_projekt_1_1_models_1_1_lesson_model.html", null ],
        [ "Projekt.Models.LoginModel", "class_projekt_1_1_models_1_1_login_model.html", null ],
        [ "Projekt.Models.MajorDataModel", "class_projekt_1_1_models_1_1_major_data_model.html", null ],
        [ "Projekt.Models.MajorModel", "class_projekt_1_1_models_1_1_major_model.html", null ],
        [ "Projekt.ViewModels.ConditionalContentControlViewModel", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model.html", [
          [ "Projekt.ViewModels.MainMenuViewModel", "class_projekt_1_1_view_models_1_1_main_menu_view_model.html", null ],
          [ "Projekt.ViewModels.MainWindowViewModel", "class_projekt_1_1_view_models_1_1_main_window_view_model.html", null ]
        ] ],
        [ "Projekt.ViewModels.CurrentProfileViewModel", "class_projekt_1_1_view_models_1_1_current_profile_view_model.html", null ],
        [ "Projekt.ViewModels.DegreeCreateViewModel", "class_projekt_1_1_view_models_1_1_degree_create_view_model.html", null ],
        [ "Projekt.ViewModels.FacultyCreateViewModel", "class_projekt_1_1_view_models_1_1_faculty_create_view_model.html", null ],
        [ "Projekt.ViewModels.GroupCreateViewModel", "class_projekt_1_1_view_models_1_1_group_create_view_model.html", null ],
        [ "Projekt.ViewModels.GroupDeleteViewModel", "class_projekt_1_1_view_models_1_1_group_delete_view_model.html", null ],
        [ "Projekt.ViewModels.GroupEditViewModel", "class_projekt_1_1_view_models_1_1_group_edit_view_model.html", null ],
        [ "Projekt.ViewModels.GroupViewTableViewModel", "class_projekt_1_1_view_models_1_1_group_view_table_view_model.html", null ],
        [ "Projekt.ViewModels.LessonsCreateViewModel", "class_projekt_1_1_view_models_1_1_lessons_create_view_model.html", null ],
        [ "Projekt.ViewModels.LessonsDeleteViewModel", "class_projekt_1_1_view_models_1_1_lessons_delete_view_model.html", null ],
        [ "Projekt.ViewModels.LessonsEditViewModel", "class_projekt_1_1_view_models_1_1_lessons_edit_view_model.html", null ],
        [ "Projekt.ViewModels.LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
        [ "Projekt.ViewModels.LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
        [ "Projekt.ViewModels.MajorManagmentViewModel", "class_projekt_1_1_view_models_1_1_major_managment_view_model.html", null ],
        [ "Projekt.ViewModels.PlaceCreateViewModel", "class_projekt_1_1_view_models_1_1_place_create_view_model.html", null ],
        [ "Projekt.ViewModels.PlaceDeleteViewModel", "class_projekt_1_1_view_models_1_1_place_delete_view_model.html", null ],
        [ "Projekt.ViewModels.PlaceEditViewModel", "class_projekt_1_1_view_models_1_1_place_edit_view_model.html", null ],
        [ "Projekt.ViewModels.PlaceViewTableViewModel", "class_projekt_1_1_view_models_1_1_place_view_table_view_model.html", null ],
        [ "Projekt.ViewModels.SubjectCreateViewModel", "class_projekt_1_1_view_models_1_1_subject_create_view_model.html", null ],
        [ "Projekt.ViewModels.SubjectDeleteViewModel", "class_projekt_1_1_view_models_1_1_subject_delete_view_model.html", null ],
        [ "Projekt.ViewModels.SubjectEditViewModel", "class_projekt_1_1_view_models_1_1_subject_edit_view_model.html", null ],
        [ "Projekt.ViewModels.SubjectViewTableViewModel", "class_projekt_1_1_view_models_1_1_subject_view_table_view_model.html", null ],
        [ "Projekt.ViewModels.TableViewModel", "class_projekt_1_1_view_models_1_1_table_view_model.html", [
          [ "Projekt.ViewModels.FacultyEditViewModel", "class_projekt_1_1_view_models_1_1_faculty_edit_view_model.html", null ],
          [ "Projekt.ViewModels.UsersEditViewModel", "class_projekt_1_1_view_models_1_1_users_edit_view_model.html", null ]
        ] ],
        [ "Projekt.ViewModels.TwoDataGridsViewModel", "class_projekt_1_1_view_models_1_1_two_data_grids_view_model.html", [
          [ "Projekt.ViewModels.GroupStudentViewModel", "class_projekt_1_1_view_models_1_1_group_student_view_model.html", null ]
        ] ],
        [ "Projekt.ViewModels.TwoListBoxesViewModel", "class_projekt_1_1_view_models_1_1_two_list_boxes_view_model.html", [
          [ "Projekt.ViewModels.GroupSubjectCoordinatorViewModel", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model.html", null ]
        ] ],
        [ "Projekt.ViewModels.UsersCreateViewModel", "class_projekt_1_1_view_models_1_1_users_create_view_model.html", null ],
        [ "Projekt.ViewModels.UsersDeleteViewModel", "class_projekt_1_1_view_models_1_1_users_delete_view_model.html", null ]
      ] ]
    ] ],
    [ "System.Windows.Markup.InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "Projekt.ViewModels.IPageViewModel", "interface_projekt_1_1_view_models_1_1_i_page_view_model.html", [
      [ "Projekt.ViewModels.ConditionalContentControlViewModel", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model.html", null ],
      [ "Projekt.ViewModels.CurrentProfileViewModel", "class_projekt_1_1_view_models_1_1_current_profile_view_model.html", null ],
      [ "Projekt.ViewModels.DegreeCreateViewModel", "class_projekt_1_1_view_models_1_1_degree_create_view_model.html", null ],
      [ "Projekt.ViewModels.FacultyCreateViewModel", "class_projekt_1_1_view_models_1_1_faculty_create_view_model.html", null ],
      [ "Projekt.ViewModels.FacultyEditViewModel", "class_projekt_1_1_view_models_1_1_faculty_edit_view_model.html", null ],
      [ "Projekt.ViewModels.GroupCreateViewModel", "class_projekt_1_1_view_models_1_1_group_create_view_model.html", null ],
      [ "Projekt.ViewModels.GroupDeleteViewModel", "class_projekt_1_1_view_models_1_1_group_delete_view_model.html", null ],
      [ "Projekt.ViewModels.GroupEditViewModel", "class_projekt_1_1_view_models_1_1_group_edit_view_model.html", null ],
      [ "Projekt.ViewModels.GroupStudentViewModel", "class_projekt_1_1_view_models_1_1_group_student_view_model.html", null ],
      [ "Projekt.ViewModels.GroupSubjectCoordinatorViewModel", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model.html", null ],
      [ "Projekt.ViewModels.GroupViewTableViewModel", "class_projekt_1_1_view_models_1_1_group_view_table_view_model.html", null ],
      [ "Projekt.ViewModels.LessonsCreateViewModel", "class_projekt_1_1_view_models_1_1_lessons_create_view_model.html", null ],
      [ "Projekt.ViewModels.LessonsDeleteViewModel", "class_projekt_1_1_view_models_1_1_lessons_delete_view_model.html", null ],
      [ "Projekt.ViewModels.LessonsEditViewModel", "class_projekt_1_1_view_models_1_1_lessons_edit_view_model.html", null ],
      [ "Projekt.ViewModels.LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
      [ "Projekt.ViewModels.LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
      [ "Projekt.ViewModels.MainMenuViewModel", "class_projekt_1_1_view_models_1_1_main_menu_view_model.html", null ],
      [ "Projekt.ViewModels.MajorManagmentViewModel", "class_projekt_1_1_view_models_1_1_major_managment_view_model.html", null ],
      [ "Projekt.ViewModels.PlaceCreateViewModel", "class_projekt_1_1_view_models_1_1_place_create_view_model.html", null ],
      [ "Projekt.ViewModels.PlaceDeleteViewModel", "class_projekt_1_1_view_models_1_1_place_delete_view_model.html", null ],
      [ "Projekt.ViewModels.PlaceEditViewModel", "class_projekt_1_1_view_models_1_1_place_edit_view_model.html", null ],
      [ "Projekt.ViewModels.PlaceViewTableViewModel", "class_projekt_1_1_view_models_1_1_place_view_table_view_model.html", null ],
      [ "Projekt.ViewModels.SubjectCreateViewModel", "class_projekt_1_1_view_models_1_1_subject_create_view_model.html", null ],
      [ "Projekt.ViewModels.SubjectDeleteViewModel", "class_projekt_1_1_view_models_1_1_subject_delete_view_model.html", null ],
      [ "Projekt.ViewModels.SubjectEditViewModel", "class_projekt_1_1_view_models_1_1_subject_edit_view_model.html", null ],
      [ "Projekt.ViewModels.SubjectViewTableViewModel", "class_projekt_1_1_view_models_1_1_subject_view_table_view_model.html", null ],
      [ "Projekt.ViewModels.UsersCreateViewModel", "class_projekt_1_1_view_models_1_1_users_create_view_model.html", null ],
      [ "Projekt.ViewModels.UsersDeleteViewModel", "class_projekt_1_1_view_models_1_1_users_delete_view_model.html", null ],
      [ "Projekt.ViewModels.UsersEditViewModel", "class_projekt_1_1_view_models_1_1_users_edit_view_model.html", null ]
    ] ],
    [ "Projekt.Models.ITable", "interface_projekt_1_1_models_1_1_i_table.html", [
      [ "Projekt.Models.GroupCreateModel", "class_projekt_1_1_models_1_1_group_create_model.html", null ],
      [ "Projekt.Models.GroupDeleteModel", "class_projekt_1_1_models_1_1_group_delete_model.html", null ],
      [ "Projekt.Models.GroupEditModel", "class_projekt_1_1_models_1_1_group_edit_model.html", null ],
      [ "Projekt.Models.LessonModel", "class_projekt_1_1_models_1_1_lesson_model.html", null ],
      [ "Projekt.Models.PlaceCreateModel", "class_projekt_1_1_models_1_1_place_create_model.html", null ]
    ] ],
    [ "Projekt.ViewModels.ITable", "interface_projekt_1_1_view_models_1_1_i_table.html", [
      [ "Projekt.ViewModels.FacultyEditViewModel", "class_projekt_1_1_view_models_1_1_faculty_edit_view_model.html", null ],
      [ "Projekt.ViewModels.GroupStudentViewModel", "class_projekt_1_1_view_models_1_1_group_student_view_model.html", null ],
      [ "Projekt.ViewModels.MajorManagmentViewModel", "class_projekt_1_1_view_models_1_1_major_managment_view_model.html", null ],
      [ "Projekt.ViewModels.UsersEditViewModel", "class_projekt_1_1_view_models_1_1_users_edit_view_model.html", null ]
    ] ],
    [ "Projekt.Models.PlaceModel", "class_projekt_1_1_models_1_1_place_model.html", null ],
    [ "Fluent.RibbonWindow", null, [
      [ "Projekt.Views.MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", null ],
      [ "Projekt.Views.MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", null ],
      [ "Projekt.Views.MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", null ]
    ] ],
    [ "Projekt.Models.SubjectModel", "class_projekt_1_1_models_1_1_subject_model.html", null ],
    [ "System.Windows.Controls.UserControl", null, [
      [ "Projekt.Views.ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", null ],
      [ "Projekt.Views.ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", null ],
      [ "Projekt.Views.ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", null ],
      [ "Projekt.Views.CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", null ],
      [ "Projekt.Views.CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", null ],
      [ "Projekt.Views.CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", null ],
      [ "Projekt.Views.DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", null ],
      [ "Projekt.Views.DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", null ],
      [ "Projekt.Views.DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", null ],
      [ "Projekt.Views.FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", null ],
      [ "Projekt.Views.FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", null ],
      [ "Projekt.Views.FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", null ],
      [ "Projekt.Views.GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", null ],
      [ "Projekt.Views.GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", null ],
      [ "Projekt.Views.GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", null ],
      [ "Projekt.Views.GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", null ],
      [ "Projekt.Views.GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", null ],
      [ "Projekt.Views.GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", null ],
      [ "Projekt.Views.GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", null ],
      [ "Projekt.Views.GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", null ],
      [ "Projekt.Views.GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", null ],
      [ "Projekt.Views.GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", null ],
      [ "Projekt.Views.GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", null ],
      [ "Projekt.Views.GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", null ],
      [ "Projekt.Views.GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", null ],
      [ "Projekt.Views.GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", null ],
      [ "Projekt.Views.GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", null ],
      [ "Projekt.Views.GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", null ],
      [ "Projekt.Views.GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", null ],
      [ "Projekt.Views.GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", null ],
      [ "Projekt.Views.LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", null ],
      [ "Projekt.Views.LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", null ],
      [ "Projekt.Views.LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", null ],
      [ "Projekt.Views.LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", null ],
      [ "Projekt.Views.LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", null ],
      [ "Projekt.Views.LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", null ],
      [ "Projekt.Views.LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", null ],
      [ "Projekt.Views.LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", null ],
      [ "Projekt.Views.LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", null ],
      [ "Projekt.Views.LoginView", "class_projekt_1_1_views_1_1_login_view.html", null ],
      [ "Projekt.Views.LoginView", "class_projekt_1_1_views_1_1_login_view.html", null ],
      [ "Projekt.Views.LoginView", "class_projekt_1_1_views_1_1_login_view.html", null ],
      [ "Projekt.Views.MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", null ],
      [ "Projekt.Views.MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", null ],
      [ "Projekt.Views.MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", null ],
      [ "Projekt.Views.MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", null ],
      [ "Projekt.Views.MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", null ],
      [ "Projekt.Views.MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", null ],
      [ "Projekt.Views.PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", null ],
      [ "Projekt.Views.PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", null ],
      [ "Projekt.Views.PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", null ],
      [ "Projekt.Views.PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", null ],
      [ "Projekt.Views.PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", null ],
      [ "Projekt.Views.PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", null ],
      [ "Projekt.Views.PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", null ],
      [ "Projekt.Views.PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", null ],
      [ "Projekt.Views.PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", null ],
      [ "Projekt.Views.PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", null ],
      [ "Projekt.Views.PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", null ],
      [ "Projekt.Views.PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", null ],
      [ "Projekt.Views.SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", null ],
      [ "Projekt.Views.SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", null ],
      [ "Projekt.Views.SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", null ],
      [ "Projekt.Views.SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", null ],
      [ "Projekt.Views.SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", null ],
      [ "Projekt.Views.SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", null ],
      [ "Projekt.Views.SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", null ],
      [ "Projekt.Views.SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", null ],
      [ "Projekt.Views.SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", null ],
      [ "Projekt.Views.SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", null ],
      [ "Projekt.Views.SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", null ],
      [ "Projekt.Views.SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", null ],
      [ "Projekt.Views.TableView", "class_projekt_1_1_views_1_1_table_view.html", null ],
      [ "Projekt.Views.TableView", "class_projekt_1_1_views_1_1_table_view.html", null ],
      [ "Projekt.Views.TableView", "class_projekt_1_1_views_1_1_table_view.html", null ],
      [ "Projekt.Views.TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", null ],
      [ "Projekt.Views.TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", null ],
      [ "Projekt.Views.TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", null ],
      [ "Projekt.Views.TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", null ],
      [ "Projekt.Views.TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", null ],
      [ "Projekt.Views.TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", null ],
      [ "Projekt.Views.TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", null ],
      [ "Projekt.Views.TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", null ],
      [ "Projekt.Views.TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", null ],
      [ "Projekt.Views.UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", null ],
      [ "Projekt.Views.UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", null ],
      [ "Projekt.Views.UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", null ],
      [ "Projekt.Views.UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", null ],
      [ "Projekt.Views.UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", null ],
      [ "Projekt.Views.UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", null ],
      [ "Projekt.Views.UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", null ],
      [ "Projekt.Views.UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", null ],
      [ "Projekt.Views.UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", null ]
    ] ],
    [ "Projekt.Models.UserModel", "class_projekt_1_1_models_1_1_user_model.html", null ]
];