var namespace_projekt_1_1_view_models =
[
    [ "Behaviors", "namespace_projekt_1_1_view_models_1_1_behaviors.html", "namespace_projekt_1_1_view_models_1_1_behaviors" ],
    [ "ConditionalContentControlViewModel", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model.html", "class_projekt_1_1_view_models_1_1_conditional_content_control_view_model" ],
    [ "CurrentProfileViewModel", "class_projekt_1_1_view_models_1_1_current_profile_view_model.html", null ],
    [ "DegreeCreateViewModel", "class_projekt_1_1_view_models_1_1_degree_create_view_model.html", null ],
    [ "FacultyCreateViewModel", "class_projekt_1_1_view_models_1_1_faculty_create_view_model.html", null ],
    [ "FacultyEditViewModel", "class_projekt_1_1_view_models_1_1_faculty_edit_view_model.html", null ],
    [ "GroupCreateViewModel", "class_projekt_1_1_view_models_1_1_group_create_view_model.html", null ],
    [ "GroupDeleteViewModel", "class_projekt_1_1_view_models_1_1_group_delete_view_model.html", null ],
    [ "GroupEditViewModel", "class_projekt_1_1_view_models_1_1_group_edit_view_model.html", null ],
    [ "GroupStudentViewModel", "class_projekt_1_1_view_models_1_1_group_student_view_model.html", "class_projekt_1_1_view_models_1_1_group_student_view_model" ],
    [ "GroupSubjectCoordinatorViewModel", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model.html", "class_projekt_1_1_view_models_1_1_group_subject_coordinator_view_model" ],
    [ "GroupViewTableViewModel", "class_projekt_1_1_view_models_1_1_group_view_table_view_model.html", null ],
    [ "IndexableProperty< T >", "class_projekt_1_1_view_models_1_1_indexable_property-1-g.html", null ],
    [ "IPageViewModel", "interface_projekt_1_1_view_models_1_1_i_page_view_model.html", null ],
    [ "ITable", "interface_projekt_1_1_view_models_1_1_i_table.html", null ],
    [ "LessonsCreateViewModel", "class_projekt_1_1_view_models_1_1_lessons_create_view_model.html", null ],
    [ "LessonsDeleteViewModel", "class_projekt_1_1_view_models_1_1_lessons_delete_view_model.html", null ],
    [ "LessonsEditViewModel", "class_projekt_1_1_view_models_1_1_lessons_edit_view_model.html", null ],
    [ "LoginViewModel", "class_projekt_1_1_view_models_1_1_login_view_model.html", null ],
    [ "MainMenuViewModel", "class_projekt_1_1_view_models_1_1_main_menu_view_model.html", null ],
    [ "MainWindowViewModel", "class_projekt_1_1_view_models_1_1_main_window_view_model.html", null ],
    [ "MajorManagmentViewModel", "class_projekt_1_1_view_models_1_1_major_managment_view_model.html", "class_projekt_1_1_view_models_1_1_major_managment_view_model" ],
    [ "PlaceCreateViewModel", "class_projekt_1_1_view_models_1_1_place_create_view_model.html", null ],
    [ "PlaceDeleteViewModel", "class_projekt_1_1_view_models_1_1_place_delete_view_model.html", null ],
    [ "PlaceEditViewModel", "class_projekt_1_1_view_models_1_1_place_edit_view_model.html", null ],
    [ "PlaceViewTableViewModel", "class_projekt_1_1_view_models_1_1_place_view_table_view_model.html", null ],
    [ "RelayCommand", "class_projekt_1_1_view_models_1_1_relay_command.html", "class_projekt_1_1_view_models_1_1_relay_command" ],
    [ "SubjectCreateViewModel", "class_projekt_1_1_view_models_1_1_subject_create_view_model.html", null ],
    [ "SubjectDeleteViewModel", "class_projekt_1_1_view_models_1_1_subject_delete_view_model.html", null ],
    [ "SubjectEditViewModel", "class_projekt_1_1_view_models_1_1_subject_edit_view_model.html", null ],
    [ "SubjectViewTableViewModel", "class_projekt_1_1_view_models_1_1_subject_view_table_view_model.html", null ],
    [ "TableViewModel", "class_projekt_1_1_view_models_1_1_table_view_model.html", null ],
    [ "TwoDataGridsViewModel", "class_projekt_1_1_view_models_1_1_two_data_grids_view_model.html", "class_projekt_1_1_view_models_1_1_two_data_grids_view_model" ],
    [ "TwoListBoxesViewModel", "class_projekt_1_1_view_models_1_1_two_list_boxes_view_model.html", null ],
    [ "UsersCreateViewModel", "class_projekt_1_1_view_models_1_1_users_create_view_model.html", null ],
    [ "UsersDeleteViewModel", "class_projekt_1_1_view_models_1_1_users_delete_view_model.html", null ],
    [ "UsersEditViewModel", "class_projekt_1_1_view_models_1_1_users_edit_view_model.html", null ]
];