var namespace_projekt_1_1_views =
[
    [ "ConditionalContentControl", "class_projekt_1_1_views_1_1_conditional_content_control.html", "class_projekt_1_1_views_1_1_conditional_content_control" ],
    [ "CurrentProfileView", "class_projekt_1_1_views_1_1_current_profile_view.html", "class_projekt_1_1_views_1_1_current_profile_view" ],
    [ "DegreeCreateView", "class_projekt_1_1_views_1_1_degree_create_view.html", "class_projekt_1_1_views_1_1_degree_create_view" ],
    [ "FacultyCreateView", "class_projekt_1_1_views_1_1_faculty_create_view.html", "class_projekt_1_1_views_1_1_faculty_create_view" ],
    [ "GroupCreateView", "class_projekt_1_1_views_1_1_group_create_view.html", "class_projekt_1_1_views_1_1_group_create_view" ],
    [ "GroupDeleteView", "class_projekt_1_1_views_1_1_group_delete_view.html", "class_projekt_1_1_views_1_1_group_delete_view" ],
    [ "GroupEditView", "class_projekt_1_1_views_1_1_group_edit_view.html", "class_projekt_1_1_views_1_1_group_edit_view" ],
    [ "GroupStudentView", "class_projekt_1_1_views_1_1_group_student_view.html", "class_projekt_1_1_views_1_1_group_student_view" ],
    [ "GroupSubjectCoordinatorView", "class_projekt_1_1_views_1_1_group_subject_coordinator_view.html", "class_projekt_1_1_views_1_1_group_subject_coordinator_view" ],
    [ "GroupTableView", "class_projekt_1_1_views_1_1_group_table_view.html", "class_projekt_1_1_views_1_1_group_table_view" ],
    [ "LessonsCreateView", "class_projekt_1_1_views_1_1_lessons_create_view.html", "class_projekt_1_1_views_1_1_lessons_create_view" ],
    [ "LessonsDeleteView", "class_projekt_1_1_views_1_1_lessons_delete_view.html", "class_projekt_1_1_views_1_1_lessons_delete_view" ],
    [ "LessonsEditView", "class_projekt_1_1_views_1_1_lessons_edit_view.html", "class_projekt_1_1_views_1_1_lessons_edit_view" ],
    [ "LoginView", "class_projekt_1_1_views_1_1_login_view.html", "class_projekt_1_1_views_1_1_login_view" ],
    [ "MainMenuView", "class_projekt_1_1_views_1_1_main_menu_view.html", "class_projekt_1_1_views_1_1_main_menu_view" ],
    [ "MainWindowView", "class_projekt_1_1_views_1_1_main_window_view.html", "class_projekt_1_1_views_1_1_main_window_view" ],
    [ "MajorManagmentView", "class_projekt_1_1_views_1_1_major_managment_view.html", "class_projekt_1_1_views_1_1_major_managment_view" ],
    [ "PlaceCreatorView", "class_projekt_1_1_views_1_1_place_creator_view.html", "class_projekt_1_1_views_1_1_place_creator_view" ],
    [ "PlaceDeleteView", "class_projekt_1_1_views_1_1_place_delete_view.html", "class_projekt_1_1_views_1_1_place_delete_view" ],
    [ "PlaceEditView", "class_projekt_1_1_views_1_1_place_edit_view.html", "class_projekt_1_1_views_1_1_place_edit_view" ],
    [ "PlaceTableView", "class_projekt_1_1_views_1_1_place_table_view.html", "class_projekt_1_1_views_1_1_place_table_view" ],
    [ "SubjectCreateView", "class_projekt_1_1_views_1_1_subject_create_view.html", "class_projekt_1_1_views_1_1_subject_create_view" ],
    [ "SubjectDeleteView", "class_projekt_1_1_views_1_1_subject_delete_view.html", "class_projekt_1_1_views_1_1_subject_delete_view" ],
    [ "SubjectEditView", "class_projekt_1_1_views_1_1_subject_edit_view.html", "class_projekt_1_1_views_1_1_subject_edit_view" ],
    [ "SubjectTableView", "class_projekt_1_1_views_1_1_subject_table_view.html", "class_projekt_1_1_views_1_1_subject_table_view" ],
    [ "TableView", "class_projekt_1_1_views_1_1_table_view.html", "class_projekt_1_1_views_1_1_table_view" ],
    [ "TimeTableView", "class_projekt_1_1_views_1_1_time_table_view.html", "class_projekt_1_1_views_1_1_time_table_view" ],
    [ "TwoDataGridsView", "class_projekt_1_1_views_1_1_two_data_grids_view.html", "class_projekt_1_1_views_1_1_two_data_grids_view" ],
    [ "TwoListBoxesView", "class_projekt_1_1_views_1_1_two_list_boxes_view.html", "class_projekt_1_1_views_1_1_two_list_boxes_view" ],
    [ "UsersCreateView", "class_projekt_1_1_views_1_1_users_create_view.html", "class_projekt_1_1_views_1_1_users_create_view" ],
    [ "UsersDeleteView", "class_projekt_1_1_views_1_1_users_delete_view.html", "class_projekt_1_1_views_1_1_users_delete_view" ],
    [ "UsersEditView", "class_projekt_1_1_views_1_1_users_edit_view.html", "class_projekt_1_1_views_1_1_users_edit_view" ]
];